server:
  port: 18003

spring:
  application:
    name: service-c #项目名称必填，在注册中心唯一；最好和之前域名保持一致，第四步会讲到原因
  cloud:
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: mse-5e117630-nacos-ans.mse.aliyuncs.com