server:
  port: 18000

spring:
  application:
    name: service-a #项目名称必填，在注册中心唯一；最好和之前域名保持一致，第四步会讲到原因
  cloud:
    security:
      open: true
      host: gov-5b8e7feabd834061804e5386ef788397.gov.nacos-ans.mse.aliyuncs.com
      port: 15012
      caAddr: gov-5b8e7feabd834061804e5386ef788397.gov.nacos-ans.mse.aliyuncs.com:15012
      initAwaitTimeS: 6000
      istiodToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IlBvbzVVVWpndDhIcXFFYWN6UUdkalVrdF94U1ktcVdybS1ITEM4ZHhtdmsifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc0OTc3NjQwNywiaWF0IjoxNzE4MjQwNDA3LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6InFoLXRlc3QtcHJlLXplcm8tdHJ1c3QiLCJwb2QiOnsibmFtZSI6InNwcmluZy1jbG91ZC1iLTdjODQ0NDc2ZC12Z243cSIsInVpZCI6ImE2MjI2YzlmLTMxZjUtNGYzNi05NmY2LWRhOGUyNTVhNDEyMyJ9LCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZGVmYXVsdCIsInVpZCI6ImU4YWYzM2E4LTczMTgtNGNmNy1iYTdhLWQxZTU2NzJhMzMzYSJ9LCJ3YXJuYWZ0ZXIiOjE3MTgyNDQwMTR9LCJuYmYiOjE3MTgyNDA0MDcsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpxaC10ZXN0LXByZS16ZXJvLXRydXN0OmRlZmF1bHQifQ.oK2DGW5Oxb5PFvkfIuDinz7FX9U9AwmBlTepJ_8DKCVuqDissDJwxHq03mzmPLLg0QNhdp_aqpkjPw_pykXrNPM9-6YcwGLQd_8ZySzjDsNbn4OH1i8utH7p-23_KEwn9F8Ki6DMZVJ6WTF4__GpdJs6IVh_TS5lm8m5xDE9tX0ODtKgpRRpx0G-y6h5lu5eOtsfd2J31xImi-HZhnuY3vD7qjyg-5knEwQ-0imKXBHCc9pQi4Yoyyu_iGJUxPLlgKtwEgIDnyjO8DnHWKbBhKk8ZptjjqhTIQVuKQyqp1UuuK8qLDOZA5t8mxBuXEMmyooGO8vbSyb9EN3npBgmgA[root@iZrj9ffvzvfdotgxpp06awZ"
      cluster-id: "sctKey"
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: mse-cce0e1c0-p.nacos-ans.mse.aliyuncs.com