server:
  port: 18000

spring:
  application:
    name: service-a #项目名称必填，在注册中心唯一；最好和之前域名保持一致，第四步会讲到原因
  cloud:
    security:
      open: true
      istiodToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkM5Q2RkOTBHWld6Ykp2cjVKaTdqM2x5T1VqYUEyTXVxanI4eV9ldHREUkkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc0MzYwOTMzMSwiaWF0IjoxNzEyMDczMzMxLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImRlZmF1bHQiLCJwb2QiOnsibmFtZSI6ImRldGFpbHMtdjEtNjVmYmM2ZmJjZi1wOWdqNiIsInVpZCI6ImVmOTY0ZGU1LTRhZDgtNGU5NS1hNjg2LWExMjE4OTQ3OGQwNiJ9LCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYm9va2luZm8tZGV0YWlscyIsInVpZCI6ImExMDYyMGJmLTc1ZTAtNDE3OC04MWE2LTM4NGFiNTYwNDI2ZCJ9LCJ3YXJuYWZ0ZXIiOjE3MTIwNzY5Mzh9LCJuYmYiOjE3MTIwNzMzMzEsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmJvb2tpbmZvLWRldGFpbHMifQ.ZyKNe49HpiCfAkA05EJWVmNDIbnvRSnMZADtDupyTcV6oPZmU7B-pjEbLZxlAx_-fH_xzCAAuASHnGUPdnPmi3MvRmOpb8ip6Nq1fLFJAioS1DBe0_bbW0OA2ny3CLSgz3Mph6EzTvCUbvHJZ0xgQsSn8kv8e9RjajIohwLhGQ8Uy01Yul5w8OUbs8Yg4Ehlf_NqwesV1PbggzrUm7bN-P4qX0SR6YOcSTmjYyF-c7icQqdLIlUQsFtese1ssrFXYvjFGOurPrAIaiBkHrNsq4y8aRKkw83raNdZJChAF7zs6Fj6v6ReF4JA9KqOfq6afvjceHaMDLj-3qq3h8ny4Q"
      initAwaitTimeS: 6000
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: mse-a8813c814-p.nacos-ans.mse.aliyuncs.com