server:
  port: 18000

spring:
  application:
    name: service-a #项目名称必填，在注册中心唯一；最好和之前域名保持一致，第四步会讲到原因
  cloud:
    security:
      open: true
      host: gov-5b8e7feabd834061804e5386ef788397.gov.nacos-ans.mse.aliyuncs.com
      port: 15012
      caAddr: gov-5b8e7feabd834061804e5386ef788397.gov.nacos-ans.mse.aliyuncs.com:15012
      initAwaitTimeS: 6000
      istiodToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkhmNlhjS2VtUGFXVEd0UW82d3hZYjE5NzlFaGRjSGVRSXJzR3piNHFGWVUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc0OTcxODQ1MiwiaWF0IjoxNzE4MTgyNDUyLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiJlZGZlOGY3YS1iMTg5LTRlNWYtOTM5Zi1mOTk2YWFlMzViZjQiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6InFoLXRlc3QtcHJlLXplcm8tdHJ1c3QiLCJub2RlIjp7Im5hbWUiOiJjbi1oYW5nemhvdS4xMC4wLjEwLjEyIiwidWlkIjoiODJmNjdiYjgtMDM5Zi00ZTgxLTk3NWItYzBhMTc0MzZmMDA5In0sInBvZCI6eyJuYW1lIjoic3ByaW5nLWNsb3VkLWEtODY5YzU4ZDZjLWRrZ3JxIiwidWlkIjoiNDI3MDI1ZTMtNDYwYy00OTFhLTlmNzYtMjM3N2MwYTQyMDhiIn0sInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJkZWZhdWx0IiwidWlkIjoiNDljOWI3M2UtYzMyYS00NThlLWIyZjMtZDBjMDBjNjhmOTZmIn0sIndhcm5hZnRlciI6MTcxODE4NjA1OX0sIm5iZiI6MTcxODE4MjQ1Miwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnFoLXRlc3QtcHJlLXplcm8tdHJ1c3Q6ZGVmYXVsdCJ9.f5D3n5o3lvV8h0Y_Sh1gQUDSkdjPOheN20sAOtG3m1QqKTzLrflkLpjUk29ZrCqx5TD8L1uoQ1_8vVEdvrTyRBHtO3tUTvkNgCQ3KOYkS2q8I4TuAtE7jSHKTjsj64_5ntZ4c9My5smc1e7rWbtg2pXmDxo2aoT3HRkJSkjvN9HXrPQXaUk4fx4OiqXrQIIGeAzvDfCpmcgWPJkeIsmvjkQDUQwUSfNVQa8-A1_1qxO8u7MZ0TevgrW4SjWv5p0epgm4vVZlioZlFGCpCQNm28nlKbub52uTu7JcbdkWcQD70Q4XL4PaSDka-dfU5DuQ6Ipnq2FbmH6O2diR0WZFmg"
      cluster-id: "sctKey"
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: mse-cce0e1c0-p.nacos-ans.mse.aliyuncs.com