server:
  port: 18001

spring:
  application:
    #项目名称必填，在注册中心唯一
    #最好和之前域名规范、kubernetes service名等保持一致（会作为调用）
    name: service-b
  cloud:
    security:
      open: true
      host: 192.168.50.62
      port: 15012
      caAddr: 192.168.50.62:15012
      istiodToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6InZ0UW4weGZqd2UzX0NTNkkwNjNLcko1WmVCNjZESTRyQVpWNFdKaElWMUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJvcGVuLXNlcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im9wZW4tc2VyZ28tdG9rZW4tZHNid2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoib3Blbi1zZXJnbyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhjOTNhZGY0LTMzNWEtNGMyMC1hNTc5LTJmMGJjMTA1ZWYxOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpvcGVuLXNlcmdvOm9wZW4tc2VyZ28ifQ.g6y98eAFtRtODdJe0-muGjGcOuk11TP6SczLyV0U7ZRvaaag0Vq3HWsKZlBYvZhkgNALiav3Rm2QQ2SVD9wDtguSKC-zh8J9IyHFafEYgfQcSGbusz-pkRIgDUPUH7yuSGuUe9bi7em854VlINU3Z6_uLzDZfyUvXmwKB5cGrUcrKROr593gl49Z9SpTGyV_1yaZpJzIY3-WrfeopRhOjqQJx0JS25-ynGhUdyA7xcC_iOdlJjuyddvoOdFpoqOLgzWGvt8b4636DtFvdeD_Lxx4k0DPsHklfaxML4fUVboruzJT2pbaNd9hWLzI1LeZ4hzqOXXSaipVc6ly3v66UA"
      initAwaitTimeS: 6000
    nacos:
      discovery: #启用 spring cloud nacos discovery
        server-addr: mse-a8813c814-p.nacos-ans.mse.aliyuncs.com